### ISSUE TITLE
jj/time crash

### ISSUE THREAD

**Issue by NijiharaTsubasa** [JixunMoe/jjBot#15]
```text
[16:0:23][MSG ]: 绅士仓库 -> Mr丶Linc : -> jj/time
[16:0:23][WARN]: User not found for uin: 4048820363

TypeError: Object Mon Jan 12 2015 16:00:23 GMT+0800 (涓浗鏍囧噯鏃堕棿) has no
method 'toLocaleFormat'
    at C:\fakepath\jjbot\plug.d\50.time.js:12:44
    at Object.<anonymous> (C:\fakepath\jjbot\core.d\Bot.Plugin.js:317:2
9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```
子进程已经退出...

**Comment by JixunMoe** [comment]
爷爷 node 没有吗。。我回去改掉

**Comment by JixunMoe** [comment]
还真没有这个方法。。回去后改掉

https://cnodejs.org/topic/51068a6cdf9e9fcc5897a8b8#510a4824df9e9fcc58e9a515
