### ISSUE TITLE
hitokoto error after setting custom uid

### ISSUE THREAD

**Issue by bbs4us** [JixunMoe/jjBot#17]
undefined:5
((__t=( hitokoto ))==null?'':__t)+
        ^
ReferenceError: hitokoto is not defined
    at Object.eval (eval at <anonymous> (/root/jjbot/node_modules/underscore/underscore.js:1329:20), <anonymous>:5:9)
    at Object.template (/root/jjbot/node_modules/underscore/underscore.js:1336:21)
    at /root/jjbot/plug.d/50.hitokoto.js:83:18
    at IncomingMessage.<anonymous> (/root/jjbot/plug.d/50.hitokoto.js:42:4)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by JixunMoe** [comment]
推送了一个更新防止因为错误配置导致抓取的错误数据被解析。

另外请检查提供的 uid，可测试 3174 (刚注册)。

**Comment by bbs4us** [comment]
发现问题了。
API 请求时加上 UID 以及 mix 和 ucat 参数时，大部分请求会报错。

**Comment by bbs4us** [comment]
我弄错了 :( 还是要加 ucat

**Comment by JixunMoe** [comment]
能否提供你给的参数
