### ISSUE TITLE
启动出现问题

### ISSUE THREAD

**Issue by masahoshiro** [JixunMoe/jjBot#18]
[20:38:1][WARN]: Fiddler is not up, http.request not patched.
[20:38:1][INFO]: vf-status: [ '1', '', '\\x00\\x00\\x00\\x00\\x16\\xed\\x66\\x67', '' ]
[20:38:1][INFO]: Need varify code, downloading image...
[20:38:1][INFO]: Request login_sig ...
[20:38:2][INFO]: vfCode downloaded, open your browser and type it.

/root/bot/jjBot/core.d/Bot.Auth.js:180
                        var newSig = data.match (/g_login_sig.*?"(.+?)"/)[1];
                                                                         ^
TypeError: Cannot read property '1' of null
    at /root/bot/jjBot/core.d/Bot.Auth.js:180:53
    at IncomingMessage.<anonymous> (/root/bot/jjBot/core.d/Bot.Auth.js:28:4)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:938:16
    at process._tickCallback (node.js:419:13)

**Comment by NijiharaTsubasa** [comment]
tx把login_sig移到了HTTP头
不过现在tx开始封杀机器人了，jjbot伪装得并不好所以一下子就会被发现……修了也登不上去……
